import { BenchmarkChart } from "@/components/charts/benchmark-chart";
import { BenchmarkInsightCards } from "@/components/inference/benchmark-insight-cards";
import { LiveBenchmarkTable } from "@/components/inference/benchmark-table";
import { StoredBenchmarkResults } from "@/components/inference/stored-benchmark-results";
import { PageHeader } from "@/components/shared/page-header";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default function BenchmarkingPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Model comparison"
        title="Benchmarking"
        description="Compare baselines and fusion architectures across spectral quality and runtime."
      />

      <BenchmarkInsightCards />

      <div className="grid gap-4 lg:grid-cols-[0.9fr_1.1fr]">
        <Card>
          <CardHeader>
            <CardTitle>Quality comparison</CardTitle>
            <CardDescription>Live run quality when available, architecture benchmark fallback otherwise.</CardDescription>
          </CardHeader>
          <CardContent>
            <BenchmarkChart />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Leaderboard</CardTitle>
            <CardDescription>Latest browser project runs compared by quality, coverage, and runtime.</CardDescription>
          </CardHeader>
          <CardContent>
            <LiveBenchmarkTable />
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Stored benchmark results</CardTitle>
          <CardDescription>Server-side benchmark records generated by completed inference runs.</CardDescription>
        </CardHeader>
        <CardContent>
          <StoredBenchmarkResults />
        </CardContent>
      </Card>
    </div>
  );
}
