import { DetectionChart } from "@/components/charts/detection-chart";
import { ResultImageGrid } from "@/components/inference/result-image-grid";
import { PageHeader } from "@/components/shared/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const maskStages = [
  ["Brightness pre-mask", 100],
  ["Cloud edge expansion", 72],
  ["Shadow projection", 64],
  ["Manual QA readiness", 40]
];

export default function CloudDetectionPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Mask generation"
        title="Cloud Detection"
        description="Review baseline cloud and cloud-shadow masks generated by the backend pipeline."
      />

      <Tabs defaultValue="overview">
        <TabsList>
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="cloud">Cloud mask</TabsTrigger>
          <TabsTrigger value="shadow">Shadow mask</TabsTrigger>
        </TabsList>
        <TabsContent className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]" value="overview">
          <Card>
            <CardHeader>
              <CardTitle>Class distribution</CardTitle>
              <CardDescription>Pixel share from the latest inference run when available.</CardDescription>
            </CardHeader>
            <CardContent>
              <DetectionChart />
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Mask stages</CardTitle>
              <CardDescription>Detection components in the CPU baseline pipeline.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {maskStages.map(([label, value]) => (
                <div className="space-y-2" key={label}>
                  <div className="flex justify-between text-sm">
                    <span>{label}</span>
                    <Badge variant="outline">{value}%</Badge>
                  </div>
                  <Progress value={Number(value)} />
                </div>
              ))}
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="cloud">
          <ResultImageGrid mode="masks" />
        </TabsContent>
        <TabsContent value="shadow">
          <ResultImageGrid mode="masks" />
        </TabsContent>
      </Tabs>
    </div>
  );
}
